"""crear tablas equipos y partidos (T006, T007)

Revision ID: 52cb67a25dcc
Revises: a221acbb7556
Create Date: 2026-09-16 18:26:21.739280

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52cb67a25dcc"
down_revision: str | Sequence[str] | None = "a221acbb7556"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column(
            "liga",
            sa.Enum(
                "PREMIER_LEAGUE", "LALIGA", "SERIE_A", "BUNDESLIGA", "LIGUE_1", name="liga_enum"
            ),
            nullable=False,
        ),
        sa.Column("tiene_historial_suficiente", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre", "liga", name="uq_equipos_nombre_liga"),
    )
    op.create_table(
        "partidos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "liga",
            sa.Enum(
                "PREMIER_LEAGUE", "LALIGA", "SERIE_A", "BUNDESLIGA", "LIGUE_1", name="liga_enum"
            ),
            nullable=False,
        ),
        sa.Column("equipo_local_id", sa.UUID(), nullable=False),
        sa.Column("equipo_visitante_id", sa.UUID(), nullable=False),
        sa.Column("fecha_kickoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "estado",
            sa.Enum("PROGRAMADO", "JUGADO", "POSPUESTO", "CANCELADO", name="estado_partido_enum"),
            nullable=False,
        ),
        sa.Column("goles_local", sa.Integer(), nullable=True),
        sa.Column("goles_visitante", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["equipo_local_id"],
            ["equipos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["equipo_visitante_id"],
            ["equipos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_partidos_fecha_kickoff_estado", "partidos", ["fecha_kickoff", "estado"], unique=False
    )
    op.create_index(op.f("ix_partidos_liga"), "partidos", ["liga"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_partidos_liga"), table_name="partidos")
    op.drop_index("ix_partidos_fecha_kickoff_estado", table_name="partidos")
    op.drop_table("partidos")
    op.drop_table("equipos")
    # ### end Alembic commands ###
